### ISSUE TITLE
AWS Elastic Graphic Error

### ISSUE THREAD

**Issue by Dogm** [unlimitedbacon/stl-thumb#25]
Hi, have problem with OpenGL Elastic Graphic (OpenGL ectensions on host VPS)

========================
c:\temp>stl-thumb.exe -f png -vv TreeFrogFridgeMagnet.stl out.png
INFO - STL File: TreeFrogFridgeMagnet.stl
INFO - Thumbnail File: out.png

INFO - Bounds:
INFO - X: -32.436058, 32.436058
Y: -27.012234, 22.989744
Z: 0.01302191, 21.957787

INFO - Center:  Point3 [0.0, -2.0112448, 10.985404]
INFO - Triangles processed:     10702

thread 'main' panicked at 'internal error: entered unreachable code', C:\Users\appveyor\.cargo\git\checkouts\glium-ba4654eea77b1028\49c12e7\src\context\capabilities.rs:281:22
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
=======================

WGLInfo64 output
=======================
WGL extensions:
    WGL_ARB_create_context, WGL_ARB_create_context_profile, 
    WGL_ARB_create_context_robustness, WGL_ARB_extensions_string, 
    WGL_ARB_make_current_read, WGL_ARB_multisample, WGL_ARB_pbuffer, 
    WGL_ARB_pixel_format, WGL_AWS_elastic_gpu, WGL_EXT_extensions_string, 
    WGL_EXT_swap_control, 
OpenGL vendor string: Amazon Web Services, Inc.
OpenGL renderer string: Amazon Elastic Graphics (eg1.medium)
OpenGL version string: 4.3.0 Compatibility Profile Context AWS 1.0.81.4465
OpenGL shading language version string: 4.30 AWS
OpenGL extensions:
    GL_AMD_seamless_cubemap_per_texture, GL_ARB_ES2_compatibility, 
    GL_ARB_ES3_compatibility, GL_ARB_arrays_of_arrays, GL_ARB_base_instance, 
    GL_ARB_blend_func_extended, GL_ARB_clear_buffer_object, 
    GL_ARB_clip_control, GL_ARB_color_buffer_float, GL_ARB_compatibility, 
    GL_ARB_compressed_texture_pixel_storage, GL_ARB_compute_shader, 
    GL_ARB_conditional_render_inverted, GL_ARB_conservative_depth, 
    GL_ARB_copy_buffer, GL_ARB_copy_image, GL_ARB_cull_distance, 
    GL_ARB_debug_output, GL_ARB_depth_buffer_float, GL_ARB_depth_clamp, 
    GL_ARB_depth_texture, GL_ARB_draw_buffers, GL_ARB_draw_buffers_blend, 
    GL_ARB_draw_elements_base_vertex, GL_ARB_draw_indirect, 
    GL_ARB_draw_instanced, GL_ARB_enhanced_layouts, 
    GL_ARB_explicit_attrib_location, GL_ARB_explicit_uniform_location, 
    GL_ARB_fragment_coord_conventions, GL_ARB_fragment_layer_viewport, 
    GL_ARB_fragment_program, GL_ARB_fragment_program_shadow, 
    GL_ARB_fragment_shader, GL_ARB_framebuffer_no_attachments, 
    GL_ARB_framebuffer_object, GL_ARB_framebuffer_sRGB, 
    GL_ARB_geometry_shader4, GL_ARB_get_program_binary, GL_ARB_gpu_shader5, 
    GL_ARB_gpu_shader_fp64, GL_ARB_half_float_pixel, GL_ARB_half_float_vertex, 
    GL_ARB_instanced_arrays, GL_ARB_internalformat_query, 
    GL_ARB_internalformat_query2, GL_ARB_invalidate_subdata, 
    GL_ARB_map_buffer_alignment, GL_ARB_map_buffer_range, 
    GL_ARB_multi_draw_indirect, GL_ARB_multisample, GL_ARB_multitexture, 
    GL_ARB_occlusion_query, GL_ARB_occlusion_query2, 
    GL_ARB_pipeline_statistics_query, GL_ARB_pixel_buffer_object, 
    GL_ARB_point_parameters, GL_ARB_point_sprite, 
    GL_ARB_program_interface_query, GL_ARB_provoking_vertex, 
    GL_ARB_query_buffer_object, GL_ARB_robust_buffer_access_behavior, 
    GL_ARB_sample_shading, GL_ARB_sampler_objects, GL_ARB_seamless_cube_map, 
    GL_ARB_separate_shader_objects, GL_ARB_shader_atomic_counters, 
    GL_ARB_shader_image_load_store, GL_ARB_shader_image_size, 
    GL_ARB_shader_objects, GL_ARB_shader_precision, 
    GL_ARB_shader_storage_buffer_object, GL_ARB_shader_subroutine, 
    GL_ARB_shader_texture_lod, GL_ARB_shading_language_100, 
    GL_ARB_shading_language_420pack, GL_ARB_shading_language_packing, 
    GL_ARB_shadow, GL_ARB_stencil_texturing, GL_ARB_sync, 
    GL_ARB_tessellation_shader, GL_ARB_texture_barrier, 
    GL_ARB_texture_border_clamp, GL_ARB_texture_buffer_object, 
    GL_ARB_texture_buffer_object_rgb32, GL_ARB_texture_buffer_range, 
    GL_ARB_texture_compression_bptc, GL_ARB_texture_compression_rgtc, 
    GL_ARB_texture_cube_map, GL_ARB_texture_cube_map_array, 
    GL_ARB_texture_env_add, GL_ARB_texture_env_combine, 
    GL_ARB_texture_env_crossbar, GL_ARB_texture_env_dot3, 
    GL_ARB_texture_float, GL_ARB_texture_gather, 
    GL_ARB_texture_mirror_clamp_to_edge, GL_ARB_texture_mirrored_repeat, 
    GL_ARB_texture_multisample, GL_ARB_texture_non_power_of_two, 
    GL_ARB_texture_query_levels, GL_ARB_texture_query_lod, 
    GL_ARB_texture_rectangle, GL_ARB_texture_rg, GL_ARB_texture_rgb10_a2ui, 
    GL_ARB_texture_stencil8, GL_ARB_texture_storage, 
    GL_ARB_texture_storage_multisample, GL_ARB_texture_swizzle, 
    GL_ARB_texture_view, GL_ARB_timer_query, GL_ARB_transform_feedback2, 
    GL_ARB_transform_feedback3, GL_ARB_transform_feedback_instanced, 
    GL_ARB_transform_feedback_overflow_query, GL_ARB_transpose_matrix, 
    GL_ARB_uniform_buffer_object, GL_ARB_vertex_array_bgra, 
    GL_ARB_vertex_array_object, GL_ARB_vertex_attrib_64bit, 
    GL_ARB_vertex_attrib_binding, GL_ARB_vertex_buffer_object, 
    GL_ARB_vertex_program, GL_ARB_vertex_shader, 
    GL_ARB_vertex_type_10f_11f_11f_rev, GL_ARB_vertex_type_2_10_10_10_rev, 
    GL_ARB_viewport_array, GL_ARB_window_pos, GL_ATI_draw_buffers, 
    GL_ATI_texture_float, GL_ATI_texture_mirror_once, GL_EXT_abgr, 
    GL_EXT_bgra, GL_EXT_blend_color, GL_EXT_blend_equation_separate, 
    GL_EXT_blend_func_separate, GL_EXT_blend_minmax, GL_EXT_blend_subtract, 
    GL_EXT_compiled_vertex_array, GL_EXT_depth_bounds_test, 
    GL_EXT_draw_buffers2, GL_EXT_draw_instanced, GL_EXT_draw_range_elements, 
    GL_EXT_fog_coord, GL_EXT_framebuffer_blit, GL_EXT_framebuffer_multisample, 
    GL_EXT_framebuffer_object, GL_EXT_framebuffer_sRGB, 
    GL_EXT_geometry_shader4, GL_EXT_gpu_program_parameters, 
    GL_EXT_gpu_shader4, GL_EXT_multi_draw_arrays, GL_EXT_packed_depth_stencil, 
    GL_EXT_packed_float, GL_EXT_packed_pixels, GL_EXT_pixel_buffer_object, 
    GL_EXT_point_parameters, GL_EXT_provoking_vertex, GL_EXT_rescale_normal, 
    GL_EXT_secondary_color, GL_EXT_separate_specular_color, 
    GL_EXT_shader_image_load_store, GL_EXT_shader_integer_mix, 
    GL_EXT_shadow_funcs, GL_EXT_stencil_wrap, GL_EXT_texture3D, 
    GL_EXT_texture_array, GL_EXT_texture_buffer_object, 
    GL_EXT_texture_compression_latc, GL_EXT_texture_compression_rgtc, 
    GL_EXT_texture_compression_s3tc, GL_EXT_texture_cube_map, 
    GL_EXT_texture_env_add, GL_EXT_texture_env_combine, 
    GL_EXT_texture_env_dot3, GL_EXT_texture_filter_anisotropic, 
    GL_EXT_texture_integer, GL_EXT_texture_lod_bias, 
    GL_EXT_texture_mirror_clamp, GL_EXT_texture_object, GL_EXT_texture_sRGB, 
    GL_EXT_texture_sRGB_decode, GL_EXT_texture_shared_exponent, 
    GL_EXT_texture_snorm, GL_EXT_texture_swizzle, GL_EXT_timer_query, 
    GL_EXT_transform_feedback, GL_EXT_vertex_array, GL_EXT_vertex_array_bgra, 
    GL_IBM_texture_mirrored_repeat, GL_KHR_context_flush_control, 
    GL_KHR_debug, GL_NV_blend_square, GL_NV_conditional_render, 
    GL_NV_copy_depth_to_color, GL_NV_copy_image, GL_NV_depth_buffer_float, 
    GL_NV_float_buffer, GL_NV_half_float, GL_NV_primitive_restart, 
    GL_NV_texgen_reflection, GL_NV_texture_barrier, GL_SGIS_generate_mipmap, 
    GL_SGIS_texture_lod, 

72 WGL Visuals
   visual   x  bf lv rg d st colorbuffer ax dp st accumbuffer  ms  cav
 id gen nat sp sz l  ci b ro  r  g  b  a bf th cl  r  g  b  a ns b eat
-----------------------------------------------------------------------
0x01  0  1  0  0  0 r  .  .  8  8  8  8  0 24  0  0  0  0  0  0 0 None
0x02  0  1  0  0  0 r  y  .  8  8  8  8  0 24  0  0  0  0  0  0 0 None
0x03  0  1  0  0  0 r  y  .  8  8  8  8  0 24  0  0  0  0  0  0 0 None
0x04  0  1  0  0  0 r  .  .  8  8  8  8  0 24  8  0  0  0  0  0 0 None
0x05  0  1  0  0  0 r  y  .  8  8  8  8  0 24  8  0  0  0  0  0 0 None
0x06  0  1  0  0  0 r  y  .  8  8  8  8  0 24  8  0  0  0  0  0 0 None
0x07  0  1  0  0  0 r  .  .  8  8  8  8  0 24  0 16 16 16 16  0 0 None
0x08  0  1  0  0  0 r  y  .  8  8  8  8  0 24  0 16 16 16 16  0 0 None
0x09  0  1  0  0  0 r  y  .  8  8  8  8  0 24  0 16 16 16 16  0 0 None
0x0a  0  1  0  0  0 r  .  .  8  8  8  8  0 24  8 16 16 16 16  0 0 None
0x0b  0  1  0  0  0 r  y  .  8  8  8  8  0 24  8 16 16 16 16  0 0 None
0x0c  0  1  0  0  0 r  y  .  8  8  8  8  0 24  8 16 16 16 16  0 0 None
0x0d  0  1  0  0  0 r  .  .  8  8  8  8  0 24  0  0  0  0  0  0 0 None
0x0e  0  1  0  0  0 r  y  .  8  8  8  8  0 24  0  0  0  0  0  0 0 None
0x0f  0  1  0  0  0 r  y  .  8  8  8  8  0 24  0  0  0  0  0  0 0 None
0x10  0  1  0  0  0 r  .  .  8  8  8  8  0 24  8  0  0  0  0  0 0 None
0x11  0  1  0  0  0 r  y  .  8  8  8  8  0 24  8  0  0  0  0  0 0 None
0x12  0  1  0  0  0 r  y  .  8  8  8  8  0 24  8  0  0  0  0  0 0 None
0x13  0  1  0  0  0 r  .  .  8  8  8  8  0 24  0  0  0  0  0  0 0 None
0x14  0  1  0  0  0 r  y  .  8  8  8  8  0 24  0  0  0  0  0  0 0 None
0x15  0  1  0  0  0 r  y  .  8  8  8  8  0 24  0  0  0  0  0  0 0 None
0x16  0  1  0  0  0 r  .  .  8  8  8  8  0 24  8  0  0  0  0  0 0 None
0x17  0  1  0  0  0 r  y  .  8  8  8  8  0 24  8  0  0  0  0  0 0 None
0x18  0  1  0  0  0 r  y  .  8  8  8  8  0 24  8  0  0  0  0  0 0 None
0x19  0  1  0  0  0 r  .  .  8  8  8  8  0 24  0  0  0  0  0  0 0 None
0x1a  0  1  0  0  0 r  y  .  8  8  8  8  0 24  0  0  0  0  0  0 0 None
0x1b  0  1  0  0  0 r  y  .  8  8  8  8  0 24  0  0  0  0  0  0 0 None
0x1c  0  1  0  0  0 r  .  .  8  8  8  8  0 24  8  0  0  0  0  0 0 None
0x1d  0  1  0  0  0 r  y  .  8  8  8  8  0 24  8  0  0  0  0  0 0 None
0x1e  0  1  0  0  0 r  y  .  8  8  8  8  0 24  8  0  0  0  0  0 0 None
0x1f  0  0  0  0  0 r  .  .  8  8  8  8  0 24  0  0  0  0  0  0 0 None
0x20  0  0  0  0  0 r  y  . 11 11 10  0  0 24  0  0  0  0  0  0 0 None
0x21  0  0  0  0  0 r  y  . 11 11 10  0  0 24  0  0  0  0  0  0 0 None
0x22  0  0  0  0  0 r  y  . 16 16 16 16  0 24  0  0  0  0  0  0 0 None
0x23  0  0  0  0  0 r  y  . 16 16 16 16  0 24  0  0  0  0  0  0 0 None
0x24  0  0  0  0  0 r  y  . 32 32 32 32  0 24  0  0  0  0  0  0 0 None
0x25  0  0  0  0  0 r  y  . 32 32 32 32  0 24  0  0  0  0  0  0 0 None
0x26  1  1  0  0  0 r  .  .  8  8  8  0  0 32  8 16 16 16  0  0 0 None
0x27  1  1  0  0  0 r  .  .  8  8  8  0  0 16  8 16 16 16  0  0 0 None
0x28  1  1  0  0  0 r  y  .  8  8  8  0  0 32  8 16 16 16  0  0 0 None
0x29  1  1  0  0  0 r  y  .  8  8  8  0  0 16  8 16 16 16  0  0 0 None
0x2a  1  1  0  0  0 r  .  .  8  8  8  8  0 32  8 16 16 16 16  0 0 None
0x2b  1  1  0  0  0 r  .  .  8  8  8  8  0 16  8 16 16 16 16  0 0 None
0x2c  1  1  0  0  0 r  y  .  8  8  8  8  0 32  8 16 16 16 16  0 0 None
0x2d  1  1  0  0  0 r  y  .  8  8  8  8  0 16  8 16 16 16 16  0 0 None
0x2e  1  1  0  0  0  c .  .  8  8  8  0  0 32  8  0  0  0  0  0 0 None
0x2f  1  1  0  0  0  c .  .  8  8  8  0  0 16  8  0  0  0  0  0 0 None
0x30  1  1  0  0  0  c y  .  8  8  8  0  0 32  8  0  0  0  0  0 0 None
0x31  1  1  0  0  0  c y  .  8  8  8  0  0 16  8  0  0  0  0  0 0 None
0x32  1  0  0  0  0 r  .  .  8  8  8  0  0 32  8 16 16 16  0  0 0 None
0x33  1  0  0  0  0 r  .  .  8  8  8  0  0 16  8 16 16 16  0  0 0 None
0x34  1  0  0  0  0 r  .  .  8  8  8  8  0 32  8 16 16 16 16  0 0 None
0x35  1  0  0  0  0 r  .  .  8  8  8  8  0 16  8 16 16 16 16  0 0 None
0x36  1  0  0  0  0  c .  .  8  8  8  0  0 32  8  0  0  0  0  0 0 None
0x37  1  0  0  0  0  c .  .  8  8  8  0  0 16  8  0  0  0  0  0 0 None
0x38  1  0  0  0  0 r  .  .  5  5  5  0  0 32  8 11 11 10  0  0 0 None
0x39  1  0  0  0  0 r  .  .  5  5  5  0  0 16  8 11 11 10  0  0 0 None
0x3a  1  0  0  0  0 r  .  .  5  5  5  8  0 32  8  8  8  8  8  0 0 None
0x3b  1  0  0  0  0 r  .  .  5  5  5  8  0 16  8  8  8  8  8  0 0 None
0x3c  1  0  0  0  0  c .  .  5  5  5  0  0 32  8  0  0  0  0  0 0 None
0x3d  1  0  0  0  0  c .  .  5  5  5  0  0 16  8  0  0  0  0  0 0 None
0x3e  1  0  0  0  0 r  .  .  3  3  2  0  0 32  8 11 11 10  0  0 0 None
0x3f  1  0  0  0  0 r  .  .  3  3  2  0  0 16  8 11 11 10  0  0 0 None
0x40  1  0  0  0  0 r  .  .  3  3  2  8  0 32  8  8  8  8  8  0 0 None
0x41  1  0  0  0  0 r  .  .  3  3  2  8  0 16  8  8  8  8  8  0 0 None
0x42  1  0  0  0  0  c .  .  3  3  2  0  0 32  8  0  0  0  0  0 0 None
0x43  1  0  0  0  0  c .  .  3  3  2  0  0 16  8  0  0  0  0  0 0 None
0x44  1  0  0  0  0 r  .  .  1  1  1  0  0 32  8  5  6  5  0  0 0 None
0x45  1  0  0  0  0 r  .  .  1  1  1  0  0 16  8  5  6  5  0  0 0 None
0x46  1  0  0  0  0 r  .  .  1  1  1  8  0 32  8  4  4  4  4  0 0 None
0x47  1  0  0  0  0 r  .  .  1  1  1  8  0 16  8  4  4  4  4  0 0 None
0x48  1  0  0  0  0  c .  .  1  1  1  0  0 32  8  0  0  0  0  0 0 None

=======================

**Comment by Dogm** [comment]
After configure RUST_BACKTRACE=1 i have this ...

----

C:\temp>stl-thumb.exe -f png -vv TreeFrogFridgeMagnet.stl out.png
INFO - STL File: TreeFrogFridgeMagnet.stl
INFO - Thumbnail File: out.png

INFO - Bounds:
INFO - X: -32.436058, 32.436058
Y: -27.012234, 22.989744
Z: 0.01302191, 21.957787

INFO - Center:  Point3 [0.0, -2.0112448, 10.985404]
INFO - Triangles processed:     10702

thread 'main' panicked at 'internal error: entered unreachable code', C:\Users\appveyor\.cargo\git\checkouts\glium-ba4654eea77b1028\49c12e7\src\context\capabilities.rs:281:22
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: BaseThreadInitThunk
  17: RtlUserThreadStart

**Comment by unlimitedbacon** [comment]
Unfortunately the backtrace doesn't reveal much other than that the error happened somewhere in Glium, the OpenGL wrapper library for Rust which we use. I'm sorry but I don't know enough about the Windows graphics stack or low level GL stuff to help you. Linux is fully supported and tested, though, if you have the option to use that.
