### ISSUE TITLE
"Failed to initialize any backend" in Nautilus on Fedora 32

### ISSUE THREAD

**Issue by smunkel** [unlimitedbacon/stl-thumb#27]
I've been spending some time trying to get this to work with Nautilus on Fedora 32, and I've been having some difficulty. I copied the `stl-thumb-mime.xml` and `stl-thumb.thumbnailer` files into the proper directories, and it seems that the thumbnails are failing. I check `~/.cache/thumbnails` and it confirms that `stl-thumb` is indeed failing. 
I tried to run the program directly using the same arguments found in `stl-thumb.thumbnailer`, and it was a success. 
Moving on from there I turned on debug logging in nautilus and enabled the full rust backtrace and I get the following: 
```
thread 'main' panicked at 'Failed to initialize any backend!
    Wayland status: NoCompositorListening
    X11 status: XOpenDisplayFailed
', /home/smunkel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.17.1/src/platform/linux/mod.rs:439:9
stack backtrace:
   0:     0x563641aefb7b - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x563641aefb7b - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x563641aefb7b - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x563641aefb7b - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x563641aefb7b - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x563641aef856 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x563641af02ed - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x56364182a9e5 - std::panicking::begin_panic::hd2cf872e4231bce0
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:411
   8:     0x563641845db2 - winit::platform::platform::EventsLoop::new::h757b1b855a4b3276
                               at /home/smunkel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.17.1/src/platform/linux/mod.rs:439
   9:     0x5636418a25c0 - winit::EventsLoop::new::he7d686194f608ef4
                               at /home/smunkel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.17.1/src/lib.rs:207
  10:     0x563641283e4e - stl_thumb::create_normal_display::h54984bd35032c2b1
                               at src/lib.rs:47
  11:     0x5636412857f8 - stl_thumb::run::h198625ed6d48084b
                               at src/lib.rs:281
  12:     0x563641281f5b - stl_thumb::main::h8168c320fa2546a6
                               at src/main.rs:36
  13:     0x563641281440 - std::rt::lang_start::{{closure}}::h948c1248301db095
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  14:     0x563641aefcf3 - std::rt::lang_start_internal::{{closure}}::h4e93c1949c7a1955
                               at src/libstd/rt.rs:49
  15:     0x563641aefcf3 - std::panicking::try::do_call::h9440ccd4dc467eaa
                               at src/libstd/panicking.rs:296
  16:     0x563641af230a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  17:     0x563641af07fd - std::panicking::try::hc046e7ee42ee744f
                               at src/libstd/panicking.rs:275
  18:     0x563641af07fd - std::panic::catch_unwind::h27dfc457c200aee0
                               at src/libstd/panic.rs:394
  19:     0x563641af07fd - std::rt::lang_start_internal::hea1b49a567afe309
                               at src/libstd/rt.rs:48
  20:     0x563641281419 - std::rt::lang_start::hf88e3fb35de2b0de
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  21:     0x5636412822ca - main
  22:     0x7f2544419042 - __libc_start_main
  23:     0x56364128122e - _start
  24:                0x0 - <unknown>
```

**Comment by unlimitedbacon** [comment]
I suspect something weird is going on with Gnome's sandboxing of thumbnailers. Can you also try running with the `-vvv` option and post the output from that?

**Comment by smunkel** [comment]
```
(org.gnome.Nautilus:23209): GnomeDesktop-DEBUG: 23:58:24.937: Failed to launch script: thread 'main' panicked at 'attempted to leave type `std::mem::ManuallyDrop<xlib_xcb::Xlib_xcb>` uninitialized, which is invalid', /home/smunkel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/mem/mod.rs:664:9
stack backtrace:
   0:     0x55e5a398b0d5 - backtrace::backtrace::libunwind::trace::h14d338b30b3ea0a7
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55e5a398b0d5 - backtrace::backtrace::trace_unsynchronized::h73ea91d74a3fd67f
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55e5a398b0d5 - std::sys_common::backtrace::_print_fmt::hd42948c952866e12
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55e5a398b0d5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha8f928866ff7571e
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55e5a39b08bc - core::fmt::write::he0c1e5f7426d2718
                               at src/libcore/fmt/mod.rs:1076
   5:     0x55e5a39883f2 - std::io::Write::write_fmt::hf3afc6cfd57d0033
                               at src/libstd/io/mod.rs:1537
   6:     0x55e5a398d590 - std::sys_common::backtrace::_print::hfc0110703f3696fd
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55e5a398d590 - std::sys_common::backtrace::print::h3f77c6990ddfaa22
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55e5a398d590 - std::panicking::default_hook::{{closure}}::heae49580a8d62d75
                               at src/libstd/panicking.rs:198
   9:     0x55e5a398d2dc - std::panicking::default_hook::hecc34e3f729e213c
                               at src/libstd/panicking.rs:217
  10:     0x55e5a398dbd3 - std::panicking::rust_panic_with_hook::he82f5d0644692441
                               at src/libstd/panicking.rs:526
  11:     0x55e5a398d7cb - rust_begin_unwind
                               at src/libstd/panicking.rs:437
  12:     0x55e5a39ae821 - core::panicking::panic_fmt::h09c929f06bb87c98
                               at src/libcore/panicking.rs:85
  13:     0x55e5a39ae76d - core::panicking::panic::h7ece43057e5422d4
                               at src/libcore/panicking.rs:50
  14:     0x55e5a38dbfe8 - core::mem::uninitialized::h352c876ae93b25eb
                               at /home/smunkel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/mem/mod.rs:664
  15:     0x55e5a38dbfe8 - x11_dl::xlib_xcb::Xlib_xcb::open::hedcd33242f61fd73
                               at /home/smunkel/.cargo/registry/src/github.com-1ecc6299db9ec823/x11-dl-2.18.3/src/link.rs:59
  16:     0x55e5a3777e98 - winit::platform::platform::x11::xdisplay::XConnection::new::h44cd1adeb1312d0a
                               at /home/smunkel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.17.1/src/platform/linux/x11/xdisplay.rs:37
  17:     0x55e5a37b775e - <winit::platform::platform::X11_BACKEND as core::ops::deref::Deref>::deref::__static_ref_initialize::h2de721747023df26
                               at /home/smunkel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.17.1/src/platform/linux/mod.rs:52
  18:     0x55e5a37b775e - core::ops::function::FnOnce::call_once::h33a5346b9357b69a
                               at /home/smunkel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:233
  19:     0x55e5a37b1bbd - lazy_static::lazy::Lazy<T>::get::{{closure}}::h950c904a2316a89b
                               at /home/smunkel/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.1.0/src/inline_lazy.rs:28
  20:     0x55e5a37c4f65 - std::sync::once::Once::call_once::{{closure}}::hf71c0895b043b940
                               at /home/smunkel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sync/once.rs:264
  21:     0x55e5a398a9aa - std::sync::once::Once::call_inner::h65ff97b0ed20a605
                               at src/libstd/sync/once.rs:416
  22:     0x55e5a37c4d01 - std::sync::once::Once::call_once::hf0b353a3e35451a5
                               at /home/smunkel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sync/once.rs:264
  23:     0x55e5a37a6ef8 - lazy_static::lazy::Lazy<T>::get::h01b4c886a8466ef1
                               at /home/smunkel/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.1.0/src/inline_lazy.rs:27
  24:     0x55e5a37a6ef8 - <winit::platform::platform::X11_BACKEND as core::ops::deref::Deref>::deref::__stability::h515263f9c7899161
                               at /home/smunkel/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.1.0/src/lib.rs:149
  25:     0x55e5a37a6ef8 - <winit::platform::platform::X11_BACKEND as core::ops::deref::Deref>::deref::h64996f0a6ea0caf2
                               at /home/smunkel/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.1.0/src/lib.rs:151
  26:     0x55e5a37a6a04 - winit::platform::platform::EventsLoop::new_x11::hce30c5ac23e85d0f
                               at /home/smunkel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.17.1/src/platform/linux/mod.rs:448
  27:     0x55e5a37a6681 - winit::platform::platform::EventsLoop::new::hf0fac2ec73f53356
                               at /home/smunkel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.17.1/src/platform/linux/mod.rs:426
  28:     0x55e5a373ec01 - winit::EventsLoop::new::h17cb5d6e95ec4766
                               at /home/smunkel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.17.1/src/lib.rs:207
  29:     0x55e5a32da239 - stl_thumb::create_normal_display::h19e30c5baaca2915
                               at src/lib.rs:47
  30:     0x55e5a32db9b0 - stl_thumb::run::ha1a02df5a5da457f
                               at src/lib.rs:281
  31:     0x55e5a32d6d47 - stl_thumb::main::h34411dbcbc883406
                               at src/main.rs:34
  32:     0x55e5a32d678b - std::rt::lang_start::{{closure}}::h44aed1ce28680012
                               at /home/smunkel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  33:     0x55e5a398dfa3 - std::rt::lang_start_internal::{{closure}}::h5d3ea623498f5f43
                               at src/libstd/rt.rs:52
  34:     0x55e5a398dfa3 - std::panicking::try::do_call::hac65e71be769a440
                               at src/libstd/panicking.rs:348
  35:     0x55e5a398dfa3 - std::panicking::try::hd4706e264bcf6712
                               at src/libstd/panicking.rs:325
  36:     0x55e5a398dfa3 - std::panic::catch_unwind::h948a0fb4a8b3ee82
                               at src/libstd/panic.rs:394
  37:     0x55e5a398dfa3 - std::rt::lang_start_internal::h72cc068ed2d0ac53
                               at src/libstd/rt.rs:51
  38:     0x55e5a32d6767 - std::rt::lang_start::hd7ab499098830a9e
                               at /home/smunkel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  39:     0x55e5a32d706a - main
  40:     0x7fef9c8ae042 - __libc_start_main
  41:     0x55e5a32d626e - _start
  42:                0x0 - <unknown>
```

**Comment by unlimitedbacon** [comment]
This is the problem, in both cases.
```
WARN - Unable to create headless GL context. Trying hidden window instead.
Reason: NoBackendAvailable(LoadingError("LibraryNotFound { descr: \"libOSMesa.so: cannot open shared object file: No such file or directory\" }"))
```
We'll need to find out why libOSMesa.so is not available.

**Comment by ssendev** [comment]
I had a similar problem on Fedora 33. 

My backtrace after manually unpacking `stl-thumb_0.3.1_amd64.deb` and moving the files into place is.

```
Failed to launch script: thread 'main' panicked at 'Failed to initialize any backend!
    Wayland status: NoCompositorListening
    X11 status: XOpenDisplayFailed
', /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.17.1/src/platform/linux/mod.rs:439:9
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: std::panicking::rust_panic_with_hook
   5: <unknown>
   6: <unknown>
   7: winit::EventsLoop::new
   8: <unknown>
   9: stl_thumb::run
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: __rust_maybe_catch_panic
  14: std::rt::lang_start_internal
  15: <unknown>
  16: __libc_start_main
  17: <unknown>
```

Running `G_MESSAGES_DEBUG=all nautilus` reveals log lines like 

```
bwrap --ro-bind /usr /usr --ro-bind /etc/ld.so.cache /etc/ld.so.cache --symlink /usr//bin /bin --symlink /usr//lib64 /lib64 --symlink /usr//lib /lib --symlink /usr//sbin /sbin --ro-bind-try /etc/alternatives /etc/alternatives --proc /proc --dev /dev --chdir / --setenv GIO_USE_VFS local --unshare-all --die-with-parent --setenv G_MESSAGES_DEBUG all --bind /tmp/gnome-desktop-thumbnailer-9RSZ10 /tmp --ro-bind /home/user/my.stl /tmp/my.stl --seccomp 28 stl-thumb -f png -s 256 /tmp/my.stl /tmp/gnome-desktop-thumbnailer.png
```

creating a bwrap wrapper that removes `--unshare-all` makes thumbnails work but is probably not the wisest decision.

**Comment by unlimitedbacon** [comment]
It's working fine in Nautils 40 running on Arch.

For comparison, here is the bwrap command:
```
bwrap --ro-bind /usr /usr --ro-bind /etc/ld.so.cache /etc/ld.so.cache --symlink /usr//bin /bin --symlink /usr//lib64 /lib64 --symlink /usr//lib /lib --symlink /usr//sbin /sbin --ro-bind-try /var/cache/fontconfig /var/cache/fontconfig --setenv GST_REGISTRY_1_0 /home/neo/.cache/gnome-desktop-thumbnailer/gstreamer-1.0/gstreamer-1.0.registry --bind /home/neo/.cache/gnome-desktop-thumbnailer/gstreamer-1.0 /home/neo/.cache/gnome-desktop-thumbnailer/gstreamer-1.0 --ro-bind-try /etc/alternatives /etc/alternatives --proc /proc --dev /dev --chdir / --setenv GIO_USE_VFS local --unshare-all --die-with-parent --setenv G_MESSAGES_DEBUG all --bind /tmp/gnome-desktop-thumbnailer-HCC510 /tmp --ro-bind /home/neo/Code/stl-thumb/test_data/sphere.stl /tmp/sphere.stl --seccomp 12 stl-thumb -f png -s 256 /tmp/sphere.stl /tmp/gnome-desktop-thumbnailer.png
```

Arch has some gstreamer stuff in the command, but I don't see how that would make a difference.

Are you guys sure that you have the `mesa-libosmesa` package installed?

**Comment by ssendev** [comment]
`mesa-libOSMesa` is installed and when removing `--unshare-all` it does work.
I just did some testing and it appears replacing `--unshare-all` with `--unshare-user-try --unshare-ipc --unshare-pid --unshare-uts --unshare-cgroup-try` also works which means `--unshare-net` is the culprit.

**Comment by unlimitedbacon** [comment]
Ok. Networking should not be required for running OpenGL. I don't know enough about Bubblewrap to know what could be going on here. Its probably worth filing a bug upstream somewhere, although I'm not sure if that should be with Fedora or Bubblewrap.

**Comment by Vaarlion** [comment]
Look to be fixed with Fedora 37
