### ISSUE TITLE
Not working on Win 10, "not yet implemented"

### ISSUE THREAD

**Issue by buergi** [unlimitedbacon/stl-thumb#32]
I can't get stl-thumb to generate any thumbnail on the Win 10 (1909 18363 and 20H2 19042), I tried it on two notebooks.
The error message I get is the same on both, namely

    C:\Program Files\stl-thumb>stl-thumb --version
    stl-thumb 0.3.1
    
    C:\Program Files\stl-thumb>stl-thumb -vv C:\temp\3DBenchy.stl C:\temp\3DBenchy.png
    INFO - STL File: C:\temp\3DBenchy.stl
    INFO - Thumbnail File: C:\temp\3DBenchy.png
    
    INFO - Bounds:
    INFO - X: -29.176, 30.825
    Y: -15.502, 15.502
    Z: 0, 48
    
    INFO - Center:  Point3 [0.8245001, 0.0, 24.0]
    INFO - Triangles processed:     225706
    
    thread 'main' panicked at 'not yet implemented', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.18.0\src\api\egl\mod.rs:546:35
    stack backtrace:
       0: <unknown>
       1: <unknown>
       2: <unknown>
       3: <unknown>
       4: <unknown>
       5: <unknown>
       6: <unknown>
       7: <unknown>
       8: <unknown>
       9: <unknown>
      10: <unknown>
      11: <unknown>
      12: <unknown>
      13: <unknown>
      14: <unknown>
      15: BaseThreadInitThunk
      16: RtlUserThreadStart

I'm not exactly sure what causes the problem, but here seems to be the corresponding line that throws the exception
https://github.com/rust-windowing/glutin/blob/v0.18.0/src/api/egl/mod.rs#L546

It seems to be something related to OpenGL... one of the notebooks has an Intel HD 520 and AMD Radeon R7 M360, the other one a GTX 1060 grapics chip.

**Comment by unlimitedbacon** [comment]
Hi. Thanks for the detailed bug report. I'm not sure what is going on here either, other than that it is failing to create an OpenGL context. If you are interested, you could compile a debug build from source in order to get a more detailed backtrace.

At some point I need to look into updating stl-thumb to use more recent versions of our OpenGL libraries, glutin and glium. I think that would help with problems like this.

**Comment by pr0gg3r** [comment]
Same problem here on my new laptop 😥

**Comment by pedrolamas** [comment]
I just experienced the same issue on my machine, I cloned the project, opened in VSCode and tried a debug with "RUST_BACKTRACE=full", and this is what I got:

```txt
INFO - STL File: D:\Users\pedro\Desktop\3DBenchy.stl
INFO - Thumbnail File: D:\Users\pedro\temp.png

INFO - Bounds:
INFO - X: -29.176, 30.825
Y: -15.502, 15.502
Z: 0, 48

INFO - Center:  Point3 [0.8245001, 0.0, 24.0]
INFO - Triangles processed:     225706

thread 'main' panicked at 'not implemented', C:\Users\pedro\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.18.0\src\api\egl\mod.rs:546:35
stack backtrace:
   0:     0x7ff65bdd5cee - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff65bdd5cee - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff65bdd5cee - std::sys_common::backtrace::_print_fmt
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\sys_common\backtrace.rs:67
   3:     0x7ff65bdd5cee - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\sys_common\backtrace.rs:46
   4:     0x7ff65bdecccb - core::fmt::write
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\fmt\mod.rs:1096
   5:     0x7ff65bdd2488 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\io\mod.rs:1568
   6:     0x7ff65bdd8b3d - std::sys_common::backtrace::_print
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\sys_common\backtrace.rs:49
   7:     0x7ff65bdd8b3d - std::sys_common::backtrace::print
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\sys_common\backtrace.rs:36
   8:     0x7ff65bdd8b3d - std::panicking::default_hook::{{closure}}
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:208
   9:     0x7ff65bdd8609 - std::panicking::default_hook
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:225
  10:     0x7ff65bdd93f0 - std::panicking::rust_panic_with_hook
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:591
  11:     0x7ff65bdd8ef3 - std::panicking::begin_panic_handler::{{closure}}
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:495
  12:     0x7ff65bdd667f - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\sys_common\backtrace.rs:141
  13:     0x7ff65bdd8e79 - std::panicking::begin_panic_handler
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:493
  14:     0x7ff65bdeab00 - core::panicking::panic_fmt
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\panicking.rs:92
  15:     0x7ff65bdeaa4c - core::panicking::panic
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\panicking.rs:50
  16:     0x7ff65bd009af - glutin::api::egl::choose_fbconfig
                               at C:\Users\pedro\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.18.0\src\api\egl\mod.rs:546
  17:     0x7ff65bcfed6c - glutin::api::egl::Context::new
                               at C:\Users\pedro\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.18.0\src\api\egl\mod.rs:256
  18:     0x7ff65bcf50fa - glutin::platform::platform::HeadlessContext::new
                               at C:\Users\pedro\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.18.0\src\platform\windows\mod.rs:123
  19:     0x7ff65b946114 - glutin::headless::HeadlessRendererBuilder::build
                               at C:\Users\pedro\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.18.0\src\headless.rs:82
  20:     0x7ff65b928c88 - stl_thumb::create_headless_display
                               at D:\Projects\stl-thumb\src\lib.rs:74
  21:     0x7ff65b929b26 - stl_thumb::render_to_image
                               at D:\Projects\stl-thumb\src\lib.rs:271
  22:     0x7ff65b92a573 - stl_thumb::render_to_file
                               at D:\Projects\stl-thumb\src\lib.rs:297
  23:     0x7ff65b921935 - stl_thumb::main
                               at D:\Projects\stl-thumb\src\main.rs:40
  24:     0x7ff65b92107b - core::ops::function::FnOnce::call_once<fn(),tuple<>>
                               at C:\Users\pedro\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
  25:     0x7ff65b92110b - std::sys_common::backtrace::__rust_begin_short_backtrace<fn(),tuple<>>
                               at C:\Users\pedro\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys_common\backtrace.rs:125
  26:     0x7ff65b921401 - std::rt::lang_start::{{closure}}<tuple<>>
                               at C:\Users\pedro\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\rt.rs:66
  27:     0x7ff65bdd9587 - core::ops::function::impls::{{impl}}::call_once
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\library\core\src\ops\function.rs:280
  28:     0x7ff65bdd9587 - std::panicking::try::do_call
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:379
  29:     0x7ff65bdd9587 - std::panicking::try
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:343
  30:     0x7ff65bdd9587 - std::panic::catch_unwind
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panic.rs:431
  31:     0x7ff65bdd9587 - std::rt::lang_start_internal
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\rt.rs:51
  32:     0x7ff65b9213d3 - std::rt::lang_start<tuple<>>
                               at C:\Users\pedro\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\rt.rs:65
  33:     0x7ff65b921d90 - main
  34:     0x7ff65bdf4670 - invoke_main
                               at D:\a01\_work\26\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  35:     0x7ff65bdf4670 - __scrt_common_main_seh
                               at D:\a01\_work\26\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  36:     0x7ffeb8797034 - BaseThreadInitThunk
  37:     0x7ffeb9162651 - RtlUserThreadStart
```

**Comment by unlimitedbacon** [comment]
This may be worth trying again with version 0.4.1
https://github.com/unlimitedbacon/stl-thumb/releases/tag/v0.4.1

**Comment by unlimitedbacon** [comment]
Closing. Please reopen if this is still happening with v0.5.0.
