### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by ehegenberger** [unlimitedbacon/stl-thumb#52]
I've installed and reinstalled several times and also repeatedly reset the thumbnail cache, all to no avail. I'm still just seeing the icon for prusaslicer that I have set as the default app. I also don't notice any thumbs.db showing up in my folders. I had my son install it on his computer as a test and it worked fine, so it must be something with my Windows setup or some other add-on I have installed. Would actually be nice to see this work.

**Comment by unlimitedbacon** [comment]
Can you try running it from the command line, with verbose output, to see what errors might be occurring?

**Comment by ehegenberger** [comment]
I guess I’m not even getting that far. I’m not sure what this means, but I must have done something wrong in the setup:

 

PS C:\Program Files\stl-thumb> .\stl-thumb Base.stl

thread 'main' panicked at 'not implemented', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.18.0\src\api\egl\mod.rs:546:35

stack backtrace:

   0:     0x7ff7ea5626fe - <unknown>

   1:     0x7ff7ea57941b - <unknown>

   2:     0x7ff7ea55f168 - <unknown>

   3:     0x7ff7ea5654fd - <unknown>

   4:     0x7ff7ea564fc9 - <unknown>

   5:     0x7ff7ea565db0 - <unknown>

   6:     0x7ff7ea5658b3 - <unknown>

   7:     0x7ff7ea56308f - <unknown>

  8:     0x7ff7ea565839 - <unknown>

   9:     0x7ff7ea577250 - <unknown>

  10:     0x7ff7ea57719c - <unknown>

  11:     0x7ff7ea5205bd - <unknown>

  12:     0x7ff7ea51dde2 - <unknown>

  13:     0x7ff7ea3fcb83 - <unknown>

  14:     0x7ff7ea4002a9 - <unknown>

  15:     0x7ff7ea3f1852 - <unknown>

  16:     0x7ff7ea3f21b6 - <unknown>

  17:     0x7ff7ea3f226c - <unknown>

  18:     0x7ff7ea565f47 - <unknown>

  19:     0x7ff7ea3f1a77 - <unknown>

  20:     0x7ff7ea580b30 - <unknown>

  21:     0x7ffd16c67034 - BaseThreadInitThunk

  22:     0x7ffd16da2651 - RtlUserThreadStart

**Comment by unlimitedbacon** [comment]
Based on where the error is happening, it looks like it might be an incompatibility with your GPU. Can you try `.\stl-thumb -vvv Base.stl` to get more info?

**Comment by ehegenberger** [comment]
Hmm. I have an Intel(R) Core(TM) i7-5700HQ CPU @ 2.70GHz and an NVIDIA GeForce GTX 980M – it’s quite an old Sager (Clevo) laptop. As far as I can tell it’s always used the integrated graphics for everything. Anyhow, here’s the verbose output. I really appreciate your quick response, but if I’m the only one having this problem I wouldn’t bother spending too much time on it, as I’ll probably be getting a new computer in another year or so. 

 

PS C:\Program Files\stl-thumb> .\stl-thumb -vvv Base.stl

INFO - STL File: Base.stl

INFO - Output: stdout

 

INFO - Bounds:

INFO - X: -49.39933, 50.60067

Y: -50.076653, 49.923347

Z: -124.39363, -6.3936286

 

INFO - Center:  Point3 [0.60066986, -0.07665253, -65.39363]

INFO - Triangles processed:     17760

 

thread 'main' panicked at 'not implemented', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.18.0\src\api\egl\mod.rs:546:35

stack backtrace:

   0:     0x7ff7ea5626fe - <unknown>

   1:     0x7ff7ea57941b - <unknown>

   2:     0x7ff7ea55f168 - <unknown>

   3:     0x7ff7ea5654fd - <unknown>

   4:     0x7ff7ea564fc9 - <unknown>

   5:     0x7ff7ea565db0 - <unknown>

   6:     0x7ff7ea5658b3 - <unknown>

   7:     0x7ff7ea56308f - <unknown>

   8:     0x7ff7ea565839 - <unknown>

   9:     0x7ff7ea577250 - <unknown>

  10:     0x7ff7ea57719c - <unknown>

  11:     0x7ff7ea5205bd - <unknown>

  12:     0x7ff7ea51dde2 - <unknown>

  13:     0x7ff7ea3fcb83 - <unknown>

  14:     0x7ff7ea4002a9 - <unknown>

  15:     0x7ff7ea3f1852 - <unknown>

  16:     0x7ff7ea3f21b6 - <unknown>

  17:     0x7ff7ea3f226c - <unknown>

  18:     0x7ff7ea565f47 - <unknown>

  19:     0x7ff7ea3f1a77 - <unknown>

  20:     0x7ff7ea580b30 - <unknown>

  21:     0x7ffd16c67034 - BaseThreadInitThunk

  22:     0x7ffd16da2651 - RtlUserThreadStart

**Comment by ehegenberger** [comment]
Just FYI, I tried installing that Marlin3DprinterTool (https://github.com/cabbagecreek/STL-thumbnail/releases) and that worked. I was afraid to try it because I thought it was going to make itself my default application, which I still want to be PrusaSlicer since that’s what I know, but evidently all it did was to set the thumbnails. I don’t know if this program is in any way related to yours, but the fact that it works might provide you with further insight. I’ll still be happy to help with any other tests if you want to pursue this further, but I now have a working solution for myself anyway.

Erich

**Comment by unlimitedbacon** [comment]
It may be worth trying again with the latest version
https://github.com/unlimitedbacon/stl-thumb/releases/tag/v0.4.1

**Comment by N6REJ** [comment]
just installed the latest and while It does show in preview pane it did not create the thumbnail cache

**Comment by ims21** [comment]
For me it not works too ... nothing happens. Used v5.0. Tried 4.1, same. I got this with 4.1
![obrazek](https://user-images.githubusercontent.com/1208763/183639186-7b617648-8d22-43fb-b2c6-d3a064410cf8.png)

**Comment by bac512** [comment]
I found it was turned off in my advanced settings.  To fix this:

Open the Start menu, type Advanced System Settings, and press Enter. Under Performance, select Settings and make sure Save taskbar thumbnail previews and Show thumbnails instead of icons are checked. Select Apply followed by OK to save any changes made.
