### ISSUE TITLE
Generates blank thumbnail

### ISSUE THREAD

**Issue by jamincollins** [unlimitedbacon/stl-thumb#94]
SSIA

```$ stl-thumb -vv '3DBenchy.stl' foo.png
INFO - STL File: 3DBenchy.stl
INFO - IMG File: foo.png
INFO - Bounds:
INFO - X: -29.176, 30.825
Y: -15.502, 15.502
Z: 0, 48

INFO - Center:	Point3 [0.8245001, 0.0, 24.0]
INFO - Triangles processed:	225706

INFO - GL Version:   Version(Gl, 2, 1)
INFO - GL Version:   2.1 Mesa 24.1.4-arch1.2
INFO - GLSL Version: Version(Gl, 1, 2)
INFO - Vendor:       AMD
INFO - Renderer      AMD Radeon Graphics (radeonsi, renoir, LLVM 18.1.8, DRM 3.57, 6.10.0-arch1-2)
INFO - Free GPU Mem: Some(88502272)
INFO - Depth Bits:   None

INFO - Scale:	0.033332776
```

Generated file shows as just transparency:
![image](https://github.com/user-attachments/assets/aeaba7bc-8c86-4b75-9706-315460d48e6f)

**Comment by Lino77** [comment]
the same by me 
INFO - STL File: Effector_Plate.stl
INFO - IMG File: out1.png
INFO - Bounds:
INFO - X: -37.627018, 36.464157
Y: -33.59598, 39.16169
Z: 0, 21.53775

INFO - Center:  Point3 [-0.58143044, 2.782854, 10.768875]
INFO - Triangles processed:     5734

warning: queue 0x5f90df5848b0 destroyed while proxies still attached:
  wl_output#13 still attached
  zwp_text_input_manager_v3#12 still attached
  xdg_activation_v1#11 still attached
  wl_subcompositor#10 still attached
  zwp_relative_pointer_manager_v1#9 still attached
  zwp_pointer_constraints_v1#8 still attached
  wl_seat#7 still attached
  wl_shm#6 still attached
  zxdg_decoration_manager_v1#5 still attached
  wl_compositor#4 still attached
  wl_registry#2 still attached
INFO - GL Version:   Version(Gl, 2, 1)
INFO - GL Version:   2.1 Mesa 24.1.6-arch1.1
INFO - GLSL Version: Version(Gl, 1, 2)
INFO - Vendor:       AMD
INFO - Renderer      AMD Radeon RX 580 Series (radeonsi, polaris10, LLVM 18.1.8, DRM 3.57, 6.10.6-arch1-1)
INFO - Free GPU Mem: Some(8279248896)
INFO - Depth Bits:   None

INFO - Scale:   0.02699377
DEBUG - View:
DEBUG - 0.894   -0.183  0.408   0.000
DEBUG - 0.447   0.365   -0.816  0.000
DEBUG - -0.000  0.913   0.408   0.000
DEBUG - -0.000  -0.000  -4.899  1.000
DEBUG - 
DEBUG - Perspective:
DEBUG - 2.799   0.000   0.000   0.000
DEBUG - 0.000   3.732   0.000   0.000
DEBUG - 0.000   0.000   -1.000  -1.000
DEBUG - 0.000   0.000   -0.200  0.000
DEBUG -

**Comment by gyscos** [comment]
Tested on the same STL file on 4 different computers all running up-to-date archlinux through ssh (so no running wayling/Xorg to use).

Failure on computer A with nvidia gpu but no running X session:
```
INFO - STL File: vase.stl
INFO - IMG File: out.png
INFO - Bounds:
INFO - X: -55, 55
Y: -55, 55
Z: 0, 230

INFO - Center:  Point3 [0.0, 0.0, 115.0]
INFO - Triangles processed:     17444

thread 'main' panicked at /home/gyscos/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.26.1/src/platform_impl/linux/mod.rs:619:9:
Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
WARN - No Wayland or X server. Falling back to osmesa software rendering. Reason Any { .. }
INFO - GL Version:   Version(Gl, 2, 1)
INFO - GL Version:   2.1 Mesa 24.2.2-arch1.1
INFO - GLSL Version: Version(Gl, 1, 2)
INFO - Vendor:       Mesa
INFO - Renderer      llvmpipe (LLVM 18.1.8, 256 bits)
INFO - Free GPU Mem: Some(0)
INFO - Depth Bits:   None

INFO - Scale:   0.008695652
DEBUG - View:
DEBUG - 0.894   -0.183  0.408   0.000
DEBUG - 0.447   0.365   -0.816  0.000
DEBUG - -0.000  0.913   0.408   0.000
DEBUG - -0.000  -0.000  -4.899  1.000
DEBUG -
DEBUG - Perspective:
DEBUG - 2.799   0.000   0.000   0.000
DEBUG - 0.000   3.732   0.000   0.000
DEBUG - 0.000   0.000   -1.000  -1.000
DEBUG - 0.000   0.000   -0.200  0.000
DEBUG -
```

Failure on computer B with AMD gpu:
```
INFO - STL File: vase.stl
INFO - IMG File: out.png
INFO - Bounds:
INFO - X: -55, 55
Y: -55, 55
Z: 0, 230

INFO - Center:  Point3 [0.0, 0.0, 115.0]
INFO - Triangles processed:     17444

thread 'main' panicked at /home/gyscos/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.26.1/src/platform_impl/linux/mod.rs:619:9:
Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
WARN - No Wayland or X server. Falling back to osmesa software rendering. Reason Any { .. }
INFO - GL Version:   Version(Gl, 2, 1)
INFO - GL Version:   2.1 Mesa 24.2.2-arch1.1
INFO - GLSL Version: Version(Gl, 1, 2)
INFO - Vendor:       Mesa
INFO - Renderer      llvmpipe (LLVM 18.1.8, 256 bits)
INFO - Free GPU Mem: Some(0)
INFO - Depth Bits:   None

INFO - Scale:   0.008695652
DEBUG - View:
DEBUG - 0.894   -0.183  0.408   0.000
DEBUG - 0.447   0.365   -0.816  0.000
DEBUG - -0.000  0.913   0.408   0.000
DEBUG - -0.000  -0.000  -4.899  1.000
DEBUG -
DEBUG - Perspective:
DEBUG - 2.799   0.000   0.000   0.000
DEBUG - 0.000   3.732   0.000   0.000
DEBUG - 0.000   0.000   -1.000  -1.000
DEBUG - 0.000   0.000   -0.200  0.000
DEBUG -
```

Success on computer C with a nvidia GPU but no running X/wayland:
```
INFO - STL File: vase.stl
INFO - IMG File: out.png
INFO - Bounds:
INFO - X: -55, 55
Y: -55, 55
Z: 0, 230

INFO - Center:  Point3 [0.0, 0.0, 115.0]
INFO - Triangles processed:     17444

thread 'main' panicked at /home/gyscos/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.26.1/src/platform_impl/linux/mod.rs:619:9:
Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
WARN - No Wayland or X server. Falling back to osmesa software rendering. Reason Any { .. }
INFO - GL Version:   Version(Gl, 2, 1)
INFO - GL Version:   2.1 Mesa 24.2.2-arch1.1
INFO - GLSL Version: Version(Gl, 1, 2)
INFO - Vendor:       Mesa
INFO - Renderer      llvmpipe (LLVM 18.1.8, 256 bits)
INFO - Free GPU Mem: Some(0)
INFO - Depth Bits:   None

INFO - Scale:   0.008695652
DEBUG - View:
DEBUG - 0.894   -0.183  0.408   0.000
DEBUG - 0.447   0.365   -0.816  0.000
DEBUG - -0.000  0.913   0.408   0.000
DEBUG - -0.000  -0.000  -4.899  1.000
DEBUG -
DEBUG - Perspective:
DEBUG - 2.799   0.000   0.000   0.000
DEBUG - 0.000   3.732   0.000   0.000
DEBUG - 0.000   0.000   -1.000  -1.000
DEBUG - 0.000   0.000   -0.200  0.000
DEBUG -
```

Success on computer D with an intel igpu:
```
INFO - STL File: vase.stl
INFO - IMG File: out.png
INFO - Bounds:
INFO - X: -55, 55
Y: -55, 55
Z: 0, 230

INFO - Center:  Point3 [0.0, 0.0, 115.0]
INFO - Triangles processed:     17444

thread 'main' panicked at /home/gyscos/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.26.1/src/platform_impl/linux/mod.rs:619:9:
Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
WARN - No Wayland or X server. Falling back to osmesa software rendering. Reason Any { .. }
INFO - GL Version:   Version(Gl, 2, 1)
INFO - GL Version:   2.1 Mesa 24.2.2-arch1.1
INFO - GLSL Version: Version(Gl, 1, 2)
INFO - Vendor:       Mesa
INFO - Renderer      llvmpipe (LLVM 18.1.8, 128 bits)
INFO - Free GPU Mem: Some(33553408)
INFO - Depth Bits:   None

INFO - Scale:   0.008695652
DEBUG - View:
DEBUG - 0.894   -0.183  0.408   0.000
DEBUG - 0.447   0.365   -0.816  0.000
DEBUG - -0.000  0.913   0.408   0.000
DEBUG - -0.000  -0.000  -4.899  1.000
DEBUG -
DEBUG - Perspective:
DEBUG - 2.799   0.000   0.000   0.000
DEBUG - 0.000   3.732   0.000   0.000
DEBUG - 0.000   0.000   -1.000  -1.000
DEBUG - 0.000   0.000   -0.200  0.000
DEBUG -
```

I'm not sure wha

**Comment by neclimdul** [comment]
Hopefully we can get an updated version in aur. as you noted in the comments of `stl-thumb-git` its based on a fork and it would be nice to run the main active repo.

**Comment by magoscur** [comment]
I confirm gyscos, stl-thumb-git will work compiling it against rust 1.79. Other options will fail.
I reinstalled my arch linux systems and this comment helps me. Thanks

**Comment by ctrlaltprocrastinate** [comment]
Got it working with `stl-thumb-git` compiled with Rust 1.85.0. Had to to modify `/usr/share/thumbnailers/stl-thumb.thumbnailer` to look like this:
```
[Thumbnailer Entry]
TryExec=stl-thumb
Exec=stl-thumb -f png -s %s %i %o
MimeType=model/stl;model/x.stl-ascii;model/x.stl-binary;application/sla;
```
